---
title: "STAT432_HW01"
author: "Taiga Hasegawa(taigah2)"
date: "2019/1/25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Question1
```{r}
data(iris)
```

a)
```{r}
levels(iris$Species)[1]="small"
levels(iris$Species)[2]="median"
levels(iris$Species)[3]="large"
```

```{r}
iris$Species
```

b)
```{r}
names(iris)[5]="Size"
names(iris)
```

c)
```{r}
library(ggplot2)
```
```{r}
ggplot(data=iris)+
  aes(x=Size,y=Petal.Length)+
  geom_boxplot()
```

d)
```{r}
fit=lm(Petal.Length~.,data=iris)
summary(fit)
```
The intercept is -1.11099 and coefficients of sepal.length is 0.60801, that of sepal width is -0.18052, that of petal.width is 0.60222, that of size(median) is 1.46337 and that of size(large) is 1.97422. The most significant variable is "median size".  

##Question2

a)
```{r}
rosenbrock=function(x){
  (1-x[1])**2+100*(x[2]-x[1]**2)**2
}
```

b)
```{r}
optim(c(3,7),rosenbrock)
optim(c(1,3),rosenbrock)
```
The minimizer is $x_1=1$ and $x_2=1$. 

c)
```{r}
#Gauss-Seidel coordinate descent algorithm
x=c(-2,9)
for (i in 1:10000000){
  if(i<4000){
    x[1]=x[1]-0.0001*(-2+2*x[1]-400*x[2]*x[1]+400*x[1]**3)
    x[2]=x[2]-0.0001*(200*x[2]-200*x[1]**2)
  }
  if(4000<=i){
    x[1]=x[1]-0.00001*(-2+2*x[1]-400*x[2]*x[1]+400*x[1]**3)
    x[2]=x[2]-0.00001*(200*x[2]-200*x[1]**2)
  }
}
```


```{r}
x
```




